- name: Configure FortiGate interface
  hosts: FG_Tunisia
  gather_facts: no
  collections:
    - fortinet.fortios.fortios
  connection: httpapi
  vars:
    ansible_connection: httpapi
    ansible_user: szbidi
    ansible_password: Cisco123*
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 80

  tasks:
  - name: Add IP address to Interface
    fortinet.fortios.fortios_system_interface:
      vdom: "root"
      state: present
      system_interface:
        interface: "<port2> (source system.interface.name)"
        allowaccess: "ping"
        ap_discover: "enable"
        description: "<Test Description>"
        ip: "192.168.50.254/24"
        name: "Inside"
    register: interface_result

