- name: Configure FortiGate interface
  hosts: FG_Tunisia
  gather_facts: no
  collections:
    - fortinet.fortios
  vars:
    interface_name: port2
    ip_address: 192.168.1.2/24
    description: Internal Network
  tasks:
    - name: Configure Interface
      fortinet.fortios.fortios_system_interface:
        vdom: "root"
        system_interface:
          name: "{{ interface_name }}"
          ip: "{{ ip_address }}"
          description: "{{ description }}"
      register: interface_result

    - name: Show Interface Configuration
      fortinet.fortios.fortios_system_interface:
        vdom: "root"
        system_interface:
          name: "{{ interface_name }}"
      register: show_result

    - name: Display Interface Configuration
      debug:
        var: show_result.stdout_lines
