- name: Configure FortiGate interface
  hosts: FG_Tunisia
  gather_facts: no
  collections:
    - fortinet.fortios.fortios
  vars:
    ansible_connection: paramiko
    ansible_user: szbidi
    ansible_password: Cisco123*

  tasks:
    - name: Add IP address to Interface
      fortinet.fortios.fortios_system_interface:
        vdom: "root"
        name: "port2"
        ip: "192.169.200.253/24"
        state: present
      register: interface_result

