- name: Configure FortiGate interface
  hosts: FG_Mexico
  gather_facts: no

  tasks:
    - name: Set interface configuration
      fortios_command:
        host: "{{ ansible_host }}"
        username: "{{ fortigate_username }}"
        password: "{{ fortigate_password }}"
        vdom: "{{ fortigate_vdom }}"
        command: "config system interface\nedit port2\nset ip 192.168.1.2/24\nend"

