- name: Configure FortiGate interface
  hosts: FG_Tunisia
  gather_facts: no
  collections:
    - fortinet.fortios.fortios
  vars:
    ansible_connection: httpapi
    ansible_user: szbidi
    ansible_password: Cisco123*
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 80

  tasks:
    - name: Add IP address to Interface
      fortinet.fortios.fortios_system_interface:
        vdom: "root"
        state: present
        system_interface:
        - name: "port2"
          description: "Test Description"
          ip: "192.168.50.254/24"
      register: interface_result

