- name: Configure FortiGate interface
  hosts: FG_Tunisia
  gather_facts: no
  collections:
    - fortinet.fortios.fortios
  vars:
    vdom: "root"
    ansible_httpapi_use_ssl: no
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 80
    interface_name: "port2"
    ip_address: "192.169.200.253/24"
    description: "Internal Network"
  tasks:
    - name: Add IP address to Interface
      fortios_system_interface:
        vdom: "{{ vdom }}"
        name: "{{ interface_name }}"
        type: "physical"
        interface: "{{ interface_name }}"
        ip: "{{ ip_address }}"
        state: present
      register: interface_result
