- name: Configure FortiGate interface
  hosts: FG_Tunisia
  gather_facts: no
  collections:
    - fortinet.fortios
  vars:
    interface_name: port2
    ip_address: 192.168.1.2/24
    description: Internal Network
  tasks:
    - name: Configure Interface
      fortios_command:
        cmd:
          - "config system interface"
          - "edit {{ interface_name }}"
          - "set ip {{ ip_address }}"
          - "set description {{ description }}"
          - "next"
          - "end"
      register: interface_result

    - name: Show Interface Configuration
      fortios_command:
        cmd: "show system interface {{ interface_name }}"
      register: show_result

    - name: Display Interface Configuration
      debug:
        var: show_result.stdout_lines
