---
- name: Créer un service sur le FortiGate FG101F
  hosts: fortigate
  gather_facts: no
  vars:
    fortigate_host: "192.168.1.1"  # Remplacez par l'adresse IP du FortiGate
    fortigate_username: "admin"    # Remplacez par le nom d'utilisateur
    fortigate_password: "password" # Remplacez par le mot de passe

  tasks:
    - name: Créer un service avec le port 444
      fortios_command:
        host: "{{ fortigate_host }}"
        username: "{{ fortigate_username }}"
        password: "{{ fortigate_password }}"
        vdom: "root"
        command: "config firewall service custom"
        nested_commands:
          - "edit my_service"
          - "set protocol TCP"
          - "set tcp-portrange 444"
          - "next"
        wait_for_completion: true
